name: build

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  push:
    # Publish `main` as Docker `latest` image.
    branches:
      - main
      - dev
      - dev-*
      - release-*
    # Publish `v1.2.3` tags as releases.
    tags:
      - v*
  # Run tests for all PRs
  pull_request:

jobs:
  build:
    uses: gertd/workflows/.github/workflows/go-build.yaml@main
    with:
    secrets: 
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
